### ISSUE TITLE
Error in sell alarm

### ISSUE THREAD

**Issue by JasonG-FR** [GarlicoinForum/NanexBot#1]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/gordane/.local/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "price_watcher.py", line 90, in on_ready
    sell_warnings, buy_warnings = get_warnings(current_price)
  File "price_watcher.py", line 51, in get_warnings
    sell_alarms = get_active_alarms("sell", price)
  File "price_watcher.py", line 42, in get_active_alarms
    cursor.execute(sql)
sqlite3.OperationalError: no such column: None

**Comment by JasonG-FR** [comment]
Added a print(sql) and tried replicating the bug but it didn't crash.

Let's wait until it crashes again.

**Comment by JasonG-FR** [comment]
Not sure if this is the same bug but : 
```
Task was destroyed but it is pending!
task: <Task pending coro=<_run_event() running at /home/gordane/.local/lib/python3.5/site-packages/discord/client.py:307> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(8)(), Task._wakeup()]>>
```
